#!/bin/bash

# Quick Reference Card

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║         Tamil Calendar & Panchangam - Quick Reference      ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "📦 PROJECT STRUCTURE"
echo "├── backend/          - Node.js Express API"
echo "├── frontend/         - React.js Web Application"
echo "├── nginx/            - Nginx Configuration"
echo "├── pm2/              - PM2 Process Manager Config"
echo "├── deployment/       - Installation & Setup Scripts"
echo "└── README.md         - Project Documentation"
echo ""

echo "🚀 QUICK START (Development)"
echo "1. cd backend && npm install && npm run dev"
echo "2. cd frontend && npm install && npm run dev"
echo "3. Frontend: http://localhost:3000"
echo "4. Backend API: http://localhost:5000"
echo ""

echo "🗄️ DATABASE"
echo "Engine:        PostgreSQL 13+"
echo "Host:          localhost:5432"
echo "Database:      tamil_calendar"
echo "User:          postgres"
echo "Password:      Password@1234"
echo ""

echo "🛠️ BACKEND SCRIPTS"
echo "npm start              - Start production server"
echo "npm run dev            - Start development with nodemon"
echo "npm run migrate        - Initialize database"
echo "npm run seed           - Create admin user"
echo "npm run backup         - Backup database"
echo "npm run restore <file> - Restore from backup"
echo ""

echo "⚛️ FRONTEND SCRIPTS"
echo "npm run dev            - Start Vite dev server"
echo "npm run build          - Build for production"
echo "npm run preview        - Preview production build"
echo ""

echo "📱 TELEGRAM BOT COMMANDS"
echo "/today                 - Today's Panchangam"
echo "/tomorrow              - Tomorrow's Panchangam"
echo "/amavasya              - New Moon dates"
echo "/pournami              - Full Moon dates"
echo "/search                - Search for a date"
echo "/help                  - Show help message"
echo ""

echo "🔐 ADMIN PANEL"
echo "URL:                   http://localhost:3000/admin/login"
echo "Default Admin:         Create with 'npm run seed'"
echo ""

echo "📡 API ENDPOINTS"
echo ""
echo "PUBLIC ENDPOINTS (No Authentication)"
echo "  GET  /api/public/today              - Today's data"
echo "  GET  /api/public/tomorrow           - Tomorrow's data"
echo "  GET  /api/public/date/:dateString   - Specific date"
echo "  GET  /api/public/month/:year/:month - Monthly calendar"
echo "  GET  /api/public/festivals          - All festivals"
echo "  GET  /api/public/amavasya           - New moon dates"
echo "  GET  /api/public/pournami           - Full moon dates"
echo "  GET  /api/public/search             - Search data"
echo ""
echo "ADMIN ENDPOINTS (JWT Required)"
echo "  POST /api/admin/login               - Admin login"
echo "  GET  /api/admin/profile             - Admin profile"
echo "  GET  /api/admin/dashboard           - Dashboard stats"
echo "  GET  /api/admin/calendar/:date      - Get calendar entry"
echo "  POST /api/admin/calendar            - Create/update entry"
echo "  POST /api/admin/calendar/:date/verify - Verify data"
echo "  GET  /api/admin/logs                - Activity logs"
echo "  POST /api/admin/logout              - Admin logout"
echo ""

echo "🐳 DOCKER DEPLOYMENT (Optional)"
echo "docker-compose up -d"
echo ""

echo "🚀 PRODUCTION DEPLOYMENT"
echo "1. Run: sudo bash deployment/install.sh"
echo "2. Configure: Edit .env file"
echo "3. Setup SSL: sudo certbot certonly --standalone -d your-domain.com"
echo "4. Start: pm2 start pm2/ecosystem.config.js --env production"
echo ""

echo "📊 MONITORING"
echo "pm2 status             - Show process status"
echo "pm2 logs               - View logs in real-time"
echo "pm2 monit              - CPU/Memory monitoring"
echo "pm2 restart all        - Restart all processes"
echo ""

echo "🔍 TROUBLESHOOTING"
echo "Port 5000 in use:      sudo lsof -i :5000"
echo "MongoDB connection:    mongosh (for testing)"
echo "Nginx config test:     sudo nginx -t"
echo "Database backup:       npm run backup"
echo ""

echo "📝 ENVIRONMENT VARIABLES (.env)"
echo "NODE_ENV               - development/production"
echo "PORT                   - API Server Port (default: 5000)"
echo "DATABASE_HOST          - PostgreSQL Host"
echo "DATABASE_PASSWORD      - PostgreSQL Password"
echo "JWT_SECRET             - JWT Secret Key"
echo "TELEGRAM_BOT_TOKEN     - Telegram Bot Token"
echo "TELEGRAM_CHANNEL_ID    - Telegram Channel ID"
echo ""

echo "📚 USEFUL LINKS"
echo "API Documentation:     http://localhost:5000/api"
echo "Admin Dashboard:       http://localhost:3000/admin"
echo "GitHub:                https://github.com/yourusername/tamil-calendar"
echo "Documentation:         /README.md"
echo ""

echo "✉️  SUPPORT"
echo "Email:                 support@tamil-calendar.local"
echo "Issues:                https://github.com/yourusername/tamil-calendar/issues"
echo ""

echo "════════════════════════════════════════════════════════════"
echo ""
